# Generated by Django 5.1.2 on 2024-11-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(default='Unknown', max_length=100)),
                ('author_last_name', models.CharField(default='Unknown', max_length=100)),
                ('birth_year', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_category_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=45)),
                ('library_address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=45)),
                ('published_year', models.DateField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='books', to='api.author')),
                ('categories', models.ManyToManyField(related_name='books', to='api.bookcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BookAtLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_quantity', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.library')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='libraries',
            field=models.ManyToManyField(through='api.BookAtLibrary', to='api.library'),
        ),
        migrations.CreateModel(
            name='LibraryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('street', models.CharField(blank=True, max_length=45, null=True)),
                ('number_of_building', models.IntegerField(blank=True, null=True)),
                ('member_first_name', models.CharField(max_length=45)),
                ('member_last_name', models.CharField(db_index=True, max_length=45)),
                ('member_gender', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('email_address', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.library')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loaned', models.DateField(blank=True, null=True)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('library_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.librarymember')),
                ('loan_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loanstatus')),
            ],
        ),
    ]
