# Generated by Django 5.1.2 on 2024-11-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarymember',
            name='member_first_name',
        ),
    ]
